/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PdfFileService } from "../pdfFile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PdfFileCreateInput } from "./PdfFileCreateInput";
import { PdfFile } from "./PdfFile";
import { PdfFileFindManyArgs } from "./PdfFileFindManyArgs";
import { PdfFileWhereUniqueInput } from "./PdfFileWhereUniqueInput";
import { PdfFileUpdateInput } from "./PdfFileUpdateInput";
import { TextExtractorFindManyArgs } from "../../textExtractor/base/TextExtractorFindManyArgs";
import { TextExtractor } from "../../textExtractor/base/TextExtractor";
import { TextExtractorWhereUniqueInput } from "../../textExtractor/base/TextExtractorWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PdfFileControllerBase {
  constructor(
    protected readonly service: PdfFileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PdfFile })
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPdfFile(
    @common.Body() data: PdfFileCreateInput
  ): Promise<PdfFile> {
    return await this.service.createPdfFile({
      data: data,
      select: {
        createdAt: true,
        fileName: true,
        filePath: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PdfFile] })
  @ApiNestedQuery(PdfFileFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pdfFiles(@common.Req() request: Request): Promise<PdfFile[]> {
    const args = plainToClass(PdfFileFindManyArgs, request.query);
    return this.service.pdfFiles({
      ...args,
      select: {
        createdAt: true,
        fileName: true,
        filePath: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PdfFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pdfFile(
    @common.Param() params: PdfFileWhereUniqueInput
  ): Promise<PdfFile | null> {
    const result = await this.service.pdfFile({
      where: params,
      select: {
        createdAt: true,
        fileName: true,
        filePath: true,
        id: true,
        updatedAt: true,
        uploadedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PdfFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePdfFile(
    @common.Param() params: PdfFileWhereUniqueInput,
    @common.Body() data: PdfFileUpdateInput
  ): Promise<PdfFile | null> {
    try {
      return await this.service.updatePdfFile({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fileName: true,
          filePath: true,
          id: true,
          updatedAt: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PdfFile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePdfFile(
    @common.Param() params: PdfFileWhereUniqueInput
  ): Promise<PdfFile | null> {
    try {
      return await this.service.deletePdfFile({
        where: params,
        select: {
          createdAt: true,
          fileName: true,
          filePath: true,
          id: true,
          updatedAt: true,
          uploadedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/textExtractors")
  @ApiNestedQuery(TextExtractorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TextExtractor",
    action: "read",
    possession: "any",
  })
  async findTextExtractors(
    @common.Req() request: Request,
    @common.Param() params: PdfFileWhereUniqueInput
  ): Promise<TextExtractor[]> {
    const query = plainToClass(TextExtractorFindManyArgs, request.query);
    const results = await this.service.findTextExtractors(params.id, {
      ...query,
      select: {
        cleanedTxtContent: true,
        createdAt: true,
        extractedAt: true,
        id: true,

        pdfFile: {
          select: {
            id: true,
          },
        },

        txtContent: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/textExtractors")
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "update",
    possession: "any",
  })
  async connectTextExtractors(
    @common.Param() params: PdfFileWhereUniqueInput,
    @common.Body() body: TextExtractorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      textExtractors: {
        connect: body,
      },
    };
    await this.service.updatePdfFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/textExtractors")
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "update",
    possession: "any",
  })
  async updateTextExtractors(
    @common.Param() params: PdfFileWhereUniqueInput,
    @common.Body() body: TextExtractorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      textExtractors: {
        set: body,
      },
    };
    await this.service.updatePdfFile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/textExtractors")
  @nestAccessControl.UseRoles({
    resource: "PdfFile",
    action: "update",
    possession: "any",
  })
  async disconnectTextExtractors(
    @common.Param() params: PdfFileWhereUniqueInput,
    @common.Body() body: TextExtractorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      textExtractors: {
        disconnect: body,
      },
    };
    await this.service.updatePdfFile({
      where: params,
      data,
      select: { id: true },
    });
  }
}
