/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { MachineLearningProcessListRelationFilter } from "../../machineLearningProcess/base/MachineLearningProcessListRelationFilter";
import { PdfFileWhereUniqueInput } from "../../pdfFile/base/PdfFileWhereUniqueInput";

@InputType()
class TextExtractorWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  cleanedTxtContent?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  extractedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MachineLearningProcessListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MachineLearningProcessListRelationFilter)
  @IsOptional()
  @Field(() => MachineLearningProcessListRelationFilter, {
    nullable: true,
  })
  machineLearningProcesses?: MachineLearningProcessListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PdfFileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PdfFileWhereUniqueInput)
  @IsOptional()
  @Field(() => PdfFileWhereUniqueInput, {
    nullable: true,
  })
  pdfFile?: PdfFileWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  txtContent?: StringNullableFilter;
}

export { TextExtractorWhereInput as TextExtractorWhereInput };
